export const TOGGLE_FAVOURITE_COUNTRY = 'TOGGLE_FAVOURITE_COUNTRY';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';
export const REQUEST_COUNTRY = 'REQUEST_COUNTRY';
export const RECEIVE_COUNTRY = 'RECEIVE_COUNTRY';